(define (domain grid_overcooked)
(:requirements :strips :equality :conditional-effects :negative-preconditions :adl :typing)
(:types 	cell agent veggieorplate - object
)

(:predicates (agent_at ?a - agent ?c - cell)
	(holding ?a - agent ?o - veggieorplate)
	(object_at ?o - veggieorplate ?c - cell)
	(is_cutting_board ?c - cell)
	(delivery_spot ?c - cell)
	(occupied ?c - cell)
	(adjacent ?c1 - cell ?c2 - cell)
	(is_floor ?c - cell)
	(holding_nothing ?a - agent)
	(tomato ?o - veggieorplate)
	(lettuce ?o - veggieorplate)
	(plate ?o - veggieorplate)
	(not-plate ?o - veggieorplate)
	(chopped ?o - veggieorplate)
	(delivered ?o - veggieorplate)
)

(:action move
	:parameters (?a - agent ?start - cell ?end - cell)
	:precondition (and (adjacent ?end ?start)
	(adjacent ?start ?end)
	(is_floor ?end)
	(is_floor ?start)
	(not (delivery_spot ?end))
	(not (delivery_spot ?start))
	(not (is_cutting_board ?end))
	(not (is_cutting_board ?start))(not (= ?start ?end)))
	:effect (and (agent_at ?a ?end)
		(not (agent_at ?a ?start))
		(occupied ?end) 
		))

(:action chop
	:parameters (?a - agent ?agent_loc - cell ?cut-board_loc - cell ?obj - veggieorplate)
	:precondition (and (is_cutting_board ?agent_loc)
	(not (agent_at ?a ?agent_loc))
	(not (delivery_spot ?agent_loc))
	(not (holding_nothing ?a))
	(not (is_floor ?agent_loc))
	(not (occupied ?agent_loc))(not (= ?agent_loc ?cut-board_loc)))
	:effect (and  
		))

(:action pickup
	:parameters (?a - agent ?agent_loc - cell ?obj_loc - cell ?obj - veggieorplate)
	:precondition (and (holding_nothing ?a)
	(not (agent_at ?a ?agent_loc))
	(not (delivery_spot ?agent_loc))
	(not (is_floor ?agent_loc))(not (= ?agent_loc ?obj_loc)))
	:effect (and (not (holding_nothing ?a)) 
		))

(:action deliver
	:parameters (?a - agent ?agent_loc - cell ?delivery_loc - cell ?obj - veggieorplate)
	:precondition (and (delivery_spot ?agent_loc)
	(not (agent_at ?a ?agent_loc))
	(not (holding_nothing ?a))
	(not (is_cutting_board ?agent_loc))
	(not (is_floor ?agent_loc))
	(not (occupied ?agent_loc))(not (= ?agent_loc ?delivery_loc)))
	:effect (and (holding_nothing ?a) 
		))

(:action merge-plate
	:parameters (?a - agent ?agent_loc - cell ?target_loc - cell ?held_obj - veggieorplate ?counter_obj - veggieorplate)
	:precondition (and (chopped ?held_obj)
	(not (agent_at ?a ?agent_loc))
	(not (delivered ?held_obj))
	(not (delivery_spot ?agent_loc))
	(not (holding ?a ?held_obj))
	(not (holding_nothing ?a))
	(not (is_floor ?agent_loc))
	(not (plate ?held_obj))
	(not-plate ?held_obj)
	(object_at ?held_obj ?agent_loc)
	(occupied ?agent_loc)(not (= ?agent_loc ?target_loc))
	(not (= ?held_obj ?counter_obj)))
	:effect (and (not (chopped ?held_obj))
		(not (object_at ?held_obj ?agent_loc))
		(not (occupied ?agent_loc)) 
		))

(:action merge-plate-on-counter
	:parameters (?a - agent ?agent_loc - cell ?target_loc - cell ?held_obj - veggieorplate ?counter_obj - veggieorplate)
	:precondition (and (not (agent_at ?a ?agent_loc))
	(not (chopped ?held_obj))
	(not (delivered ?held_obj))
	(not (delivery_spot ?agent_loc))
	(not (holding ?a ?held_obj))
	(not (holding_nothing ?a))
	(not (lettuce ?held_obj))
	(not (not-plate ?held_obj))
	(not (tomato ?held_obj))
	(plate ?held_obj)(not (= ?agent_loc ?target_loc))
	(not (= ?held_obj ?counter_obj)))
	:effect (and (not ((not-plate ?held_obj))
		(not (object_at ?held_obj ?agent_loc))
		(not (plate ?held_obj)) 
		))

(:action merge-no-plate
	:parameters (?a - agent ?agent_loc - cell ?target_loc - cell ?held_obj - veggieorplate ?counter_obj - veggieorplate)
	:precondition (and (chopped ?held_obj)
	(not (agent_at ?a ?agent_loc))
	(not (delivered ?held_obj))
	(not (delivery_spot ?agent_loc))
	(not (holding ?a ?held_obj))
	(not (holding_nothing ?a))
	(not (is_floor ?agent_loc))
	(not (plate ?held_obj))
	(not-plate ?held_obj)
	(object_at ?held_obj ?agent_loc)
	(occupied ?agent_loc)(not (= ?agent_loc ?target_loc))
	(not (= ?held_obj ?counter_obj)))
	:effect (and (not (chopped ?held_obj))
		(not (object_at ?held_obj ?agent_loc))
		(not (occupied ?agent_loc)) 
		))

(:action put-down-chopped-veggie
	:parameters (?a - agent ?agent_loc - cell ?target_loc - cell ?obj - veggieorplate)
	:precondition (and (not (agent_at ?a ?agent_loc))
	(not (delivery_spot ?agent_loc))
	(not (holding_nothing ?a))
	(not (is_floor ?agent_loc))(not (= ?agent_loc ?target_loc)))
	:effect (and (holding_nothing ?a) 
		))

(:action put-down-unchopped-veggie
	:parameters (?a - agent ?agent_loc - cell ?target_loc - cell ?obj - veggieorplate)
	:precondition (and (not (agent_at ?a ?agent_loc))
	(not (delivery_spot ?agent_loc))
	(not (holding_nothing ?a))
	(not (is_cutting_board ?agent_loc))
	(not (is_floor ?agent_loc))(not (= ?agent_loc ?target_loc)))
	:effect (and (holding_nothing ?a) 
		))

(:action put-down-plate
	:parameters (?a - agent ?agent_loc - cell ?target_loc - cell ?obj - veggieorplate)
	:precondition (and (not (agent_at ?a ?agent_loc))
	(not (delivery_spot ?agent_loc))
	(not (holding_nothing ?a))
	(not (is_floor ?agent_loc))(not (= ?agent_loc ?target_loc)))
	:effect (and (holding_nothing ?a) 
		))

)